#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXO6nwZX1/c0mFHn0aUSo24moC7hdqmCMospG0VTjiNkv286ffBKvDIrDLtQ+z4GZ2p2l5Cpj5Q+BdZ7HhoDF82WTYajfy76yPIaT/HGc1khettNH530RyrhofAWYmPWF/aAxNGsAHcRUdMeY9rCNdK9YUi8wuPOi+4lvWdbF5ySXlKV8PJ3y/CE0551lEUnsfm06hJyF4fbBrx4ycrLyCN1MpegDDn7RNOKU7lJw5Fl8jK0KHyBRfLRbYUBb/rg+rbWUOG/DS6oKBONx5G1kEL9ZCrZPRcpJl2qwTo42VyvkNOfpKcidRDY4FHdYHzE7o+/UMkMbyr4CSY/uIR3qb uika@DESKTOP-JHTBQ86

packages:
  - docker.io
  - docker-compose

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - git clone https://github.com/OlgaKonshina/HR_AI.git /app
  - cd /app && docker build -t hr-ai-app .